# Site wide configuration

title:            Mauricio Magnani
locale:           pt_BR
url:		  http://mlab.run


# Jekyll configuration

permalink:   /:year/:month/:day/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Mauricio Magnani
  avatar: mmagnani.jpg
  bio: "A guy who loves technology and new challenges!"
  email: msmagnanijr@gmail.com
  disqus-shortname: mmagnani
  twitter: msmagnanijr
  facebook: #username
  google:
    plus: #username
    analytics: UA-68660365-1
    verify:
    ad-client: "ca-pub-3315278657740846"
    ad-slot: 8102354619
  bing-verify:
  github: msmagnanijr
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: mauriciomagnanijr
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
